/*
 * Ultra-Minimal Memory Embedded Tree Ensemble Model
 * 
 * Model Metadata:
 *   - Number of trees: 5
 *   - Number of features: 8
 *   - Number of classes: 1
 *   - Task type: REGRESSION
 *   - Base score: 0.000000
 * 
 * Optimization Configuration:
 *   - Threshold precision: 2 decimal places
 *   - Leaf precision: 2 decimal places
 *   - Packed structs: Yes
 *   - Node size: 6 bytes
 *   - Total nodes: 369
 * 
 * Memory Usage:
 *   - Original: 8,896 bytes
 *   - Optimized: 3,416 bytes
 *   - Compression: 2.60x
 *   - Threshold deduplication: 182 -> 113
 *   - Leaf deduplication: 187 -> 180
 * 
 * IMPORTANT: This file is automatically generated. Do not edit manually.
 */

#ifndef EMBEDDED_TREES_MINIMAL_H
#define EMBEDDED_TREES_MINIMAL_H


#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif


/* Model constants */
#define N_TREES 5
#define N_FEATURES 8
#define N_CLASSES 1
#define N_THRESHOLDS 113
#define N_LEAVES 180
#define TASK_TYPE REGRESSION
#define BASE_SCORE 0.000000f
#define THRESHOLD_PRECISION 2
#define LEAF_PRECISION 2
#define PACK_STRUCTS 1
#define NODE_SIZE 6
#define TOTAL_NODES 369
#define ORIGINAL_MEMORY 8896
#define OPTIMIZED_MEMORY 3416
#define COMPRESSION_RATIO 2.60
#define ORIGINAL_THRESHOLDS 182
#define UNIQUE_THRESHOLDS 113
#define ORIGINAL_LEAVES 187
#define UNIQUE_LEAVES 180


/* Optimized tree node structure */
#pragma pack(push, 1)
typedef struct {
    uint8_t is_leaf : 1;  /* Bitfield for minimal bool size */
    union {
        struct {
            uint8_t feature;
            uint8_t threshold_idx;
            uint8_t left;
            uint8_t right;
        } internal;
        uint8_t leaf_idx;
    } u;
} OptNode;
#pragma pack(pop)

typedef struct {
    uint32_t start_idx;  /* Start index in global node array */
    uint16_t node_count;
} OptTree;


/* Shared data arrays for deduplication */
static const float SHARED_THRESHOLDS[N_THRESHOLDS] = { -1.39f, -1.32f, -1.31f, -1.29f, -1.22f, -1.13f, -1.01f, -0.91f, -0.88f, -0.87f, -0.82f, -0.75f, -0.74f, -0.73f, -0.69f, -0.67f, -0.64f, -0.63f, -0.62f, -0.59f, -0.58f, -0.56f, -0.55f, -0.54f, -0.53f, -0.51f, -0.50f, -0.49f, -0.48f, -0.45f, -0.41f, -0.40f, -0.39f, -0.36f, -0.35f, -0.34f, -0.33f, -0.32f, -0.29f, -0.25f, -0.24f, -0.22f, -0.20f, -0.16f, -0.15f, -0.14f, -0.12f, -0.11f, -0.10f, -0.09f, -0.08f, -0.05f, -0.04f, -0.02f, -0.01f, 0.00f, 0.01f, 0.02f, 0.04f, 0.05f, 0.06f, 0.07f, 0.08f, 0.09f, 0.10f, 0.15f, 0.17f, 0.18f, 0.19f, 0.20f, 0.21f, 0.23f, 0.24f, 0.25f, 0.27f, 0.31f, 0.33f, 0.34f, 0.37f, 0.38f, 0.39f, 0.41f, 0.43f, 0.45f, 0.46f, 0.47f, 0.48f, 0.49f, 0.50f, 0.51f, 0.53f, 0.54f, 0.57f, 0.61f, 0.65f, 0.66f, 0.69f, 0.70f, 0.73f, 0.74f, 0.80f, 0.87f, 0.92f, 0.93f, 0.95f, 0.98f, 1.02f, 1.04f, 1.09f, 1.18f, 1.19f, 1.28f, 1.33f };
static const float SHARED_LEAVES[N_LEAVES] = { -31.69f, -30.22f, -30.00f, -29.03f, -26.42f, -26.05f, -24.04f, -23.59f, -20.96f, -20.34f, -20.24f, -19.95f, -19.31f, -18.06f, -18.01f, -17.97f, -17.93f, -17.39f, -17.05f, -17.00f, -15.99f, -15.78f, -15.47f, -15.34f, -15.28f, -15.17f, -14.85f, -14.50f, -14.26f, -14.19f, -14.03f, -13.51f, -13.41f, -12.74f, -11.98f, -11.76f, -11.37f, -11.07f, -10.83f, -10.45f, -10.25f, -9.90f, -9.71f, -9.24f, -9.15f, -9.06f, -9.05f, -8.74f, -8.71f, -8.66f, -8.56f, -8.48f, -8.33f, -8.25f, -8.23f, -7.94f, -7.68f, -7.56f, -7.31f, -6.87f, -6.57f, -6.49f, -5.78f, -5.76f, -5.20f, -5.16f, -4.65f, -4.56f, -4.54f, -4.48f, -4.31f, -3.92f, -3.83f, -3.58f, -2.97f, -2.69f, -2.56f, -2.54f, -2.48f, -2.33f, -2.31f, -2.25f, -2.18f, -2.03f, -1.85f, -1.71f, -1.66f, -1.54f, -1.31f, -1.17f, -0.98f, -0.42f, 0.13f, 0.20f, 0.24f, 0.31f, 0.49f, 0.68f, 0.83f, 1.06f, 1.07f, 1.09f, 1.10f, 1.32f, 1.42f, 1.55f, 1.78f, 1.80f, 2.29f, 2.38f, 2.47f, 2.73f, 3.11f, 3.25f, 3.82f, 4.06f, 4.19f, 4.28f, 4.55f, 4.57f, 4.97f, 5.05f, 5.15f, 5.39f, 5.45f, 6.07f, 6.20f, 6.49f, 6.73f, 7.03f, 7.57f, 7.77f, 8.30f, 8.32f, 8.71f, 8.72f, 9.00f, 9.02f, 9.25f, 9.29f, 9.55f, 9.60f, 9.69f, 9.75f, 10.09f, 10.33f, 10.41f, 10.89f, 11.04f, 11.38f, 11.82f, 12.17f, 12.68f, 12.98f, 13.37f, 14.58f, 14.79f, 15.19f, 15.30f, 15.72f, 15.82f, 16.86f, 17.04f, 17.17f, 17.38f, 17.82f, 18.18f, 18.74f, 19.00f, 19.23f, 19.26f, 19.62f, 19.63f, 21.28f, 21.60f, 21.79f, 25.76f, 26.24f, 28.54f, 29.56f };


/* Single global node array */
static const OptNode NODES[TOTAL_NODES] = {
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=28}}},
    {false, {.internal={.feature=0, .threshold_idx=89, .left=2, .right=19}}},
    {false, {.internal={.feature=2, .threshold_idx=55, .left=3, .right=12}}},
    {false, {.internal={.feature=6, .threshold_idx=1, .left=4, .right=5}}},
    {true, {.leaf_idx=0}},
    {false, {.internal={.feature=4, .threshold_idx=71, .left=6, .right=9}}},
    {false, {.internal={.feature=2, .threshold_idx=5, .left=7, .right=8}}},
    {true, {.leaf_idx=1}},
    {true, {.leaf_idx=9}},
    {false, {.internal={.feature=1, .threshold_idx=52, .left=10, .right=11}}},
    {true, {.leaf_idx=11}},
    {true, {.leaf_idx=50}},
    {false, {.internal={.feature=0, .threshold_idx=9, .left=13, .right=14}}},
    {true, {.leaf_idx=17}},
    {false, {.internal={.feature=5, .threshold_idx=84, .left=15, .right=18}}},
    {false, {.internal={.feature=1, .threshold_idx=53, .left=16, .right=17}}},
    {true, {.leaf_idx=23}},
    {true, {.leaf_idx=68}},
    {true, {.leaf_idx=106}},
    {false, {.internal={.feature=2, .threshold_idx=96, .left=20, .right=27}}},
    {false, {.internal={.feature=4, .threshold_idx=106, .left=21, .right=26}}},
    {false, {.internal={.feature=2, .threshold_idx=17, .left=22, .right=23}}},
    {true, {.leaf_idx=28}},
    {false, {.internal={.feature=5, .threshold_idx=74, .left=24, .right=25}}},
    {true, {.leaf_idx=54}},
    {true, {.leaf_idx=103}},
    {true, {.leaf_idx=131}},
    {true, {.leaf_idx=145}},
    {false, {.internal={.feature=2, .threshold_idx=80, .left=29, .right=54}}},
    {false, {.internal={.feature=0, .threshold_idx=41, .left=30, .right=41}}},
    {false, {.internal={.feature=4, .threshold_idx=67, .left=31, .right=36}}},
    {false, {.internal={.feature=1, .threshold_idx=64, .left=32, .right=35}}},
    {false, {.internal={.feature=2, .threshold_idx=29, .left=33, .right=34}}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=22}},
    {true, {.leaf_idx=60}},
    {false, {.internal={.feature=6, .threshold_idx=103, .left=37, .right=40}}},
    {false, {.internal={.feature=5, .threshold_idx=44, .left=38, .right=39}}},
    {true, {.leaf_idx=30}},
    {true, {.leaf_idx=75}},
    {true, {.leaf_idx=117}},
    {false, {.internal={.feature=6, .threshold_idx=94, .left=42, .right=49}}},
    {false, {.internal={.feature=1, .threshold_idx=61, .left=43, .right=46}}},
    {false, {.internal={.feature=0, .threshold_idx=100, .left=44, .right=45}}},
    {true, {.leaf_idx=43}},
    {true, {.leaf_idx=91}},
    {false, {.internal={.feature=2, .threshold_idx=33, .left=47, .right=48}}},
    {true, {.leaf_idx=90}},
    {true, {.leaf_idx=144}},
    {false, {.internal={.feature=5, .threshold_idx=91, .left=50, .right=53}}},
    {false, {.internal={.feature=4, .threshold_idx=62, .left=51, .right=52}}},
    {true, {.leaf_idx=110}},
    {true, {.leaf_idx=150}},
    {true, {.leaf_idx=170}},
    {false, {.internal={.feature=0, .threshold_idx=30, .left=55, .right=58}}},
    {false, {.internal={.feature=6, .threshold_idx=87, .left=56, .right=57}}},
    {true, {.leaf_idx=78}},
    {true, {.leaf_idx=139}},
    {false, {.internal={.feature=1, .threshold_idx=77, .left=59, .right=64}}},
    {false, {.internal={.feature=3, .threshold_idx=86, .left=60, .right=63}}},
    {false, {.internal={.feature=0, .threshold_idx=98, .left=61, .right=62}}},
    {true, {.leaf_idx=112}},
    {true, {.leaf_idx=157}},
    {true, {.leaf_idx=169}},
    {false, {.internal={.feature=6, .threshold_idx=90, .left=65, .right=66}}},
    {true, {.leaf_idx=167}},
    {true, {.leaf_idx=179}},
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=32}}},
    {false, {.internal={.feature=0, .threshold_idx=70, .left=2, .right=19}}},
    {false, {.internal={.feature=2, .threshold_idx=56, .left=3, .right=12}}},
    {false, {.internal={.feature=6, .threshold_idx=0, .left=4, .right=5}}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=4, .threshold_idx=43, .left=6, .right=9}}},
    {false, {.internal={.feature=3, .threshold_idx=31, .left=7, .right=8}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=18}},
    {false, {.internal={.feature=1, .threshold_idx=55, .left=10, .right=11}}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=59}},
    {false, {.internal={.feature=1, .threshold_idx=83, .left=13, .right=16}}},
    {false, {.internal={.feature=6, .threshold_idx=7, .left=14, .right=15}}},
    {true, {.leaf_idx=26}},
    {true, {.leaf_idx=55}},
    {false, {.internal={.feature=5, .threshold_idx=49, .left=17, .right=18}}},
    {true, {.leaf_idx=49}},
    {true, {.leaf_idx=114}},
    {false, {.internal={.feature=2, .threshold_idx=18, .left=20, .right=23}}},
    {false, {.internal={.feature=0, .threshold_idx=104, .left=21, .right=22}}},
    {true, {.leaf_idx=24}},
    {true, {.leaf_idx=74}},
    {false, {.internal={.feature=1, .threshold_idx=90, .left=24, .right=29}}},
    {false, {.internal={.feature=6, .threshold_idx=11, .left=25, .right=28}}},
    {false, {.internal={.feature=1, .threshold_idx=26, .left=26, .right=27}}},
    {true, {.leaf_idx=57}},
    {true, {.leaf_idx=89}},
    {true, {.leaf_idx=120}},
    {false, {.internal={.feature=5, .threshold_idx=81, .left=30, .right=31}}},
    {true, {.leaf_idx=129}},
    {true, {.leaf_idx=155}},
    {false, {.internal={.feature=2, .threshold_idx=80, .left=33, .right=62}}},
    {false, {.internal={.feature=0, .threshold_idx=41, .left=34, .right=45}}},
    {false, {.internal={.feature=1, .threshold_idx=64, .left=35, .right=40}}},
    {false, {.internal={.feature=4, .threshold_idx=67, .left=36, .right=39}}},
    {false, {.internal={.feature=6, .threshold_idx=88, .left=37, .right=38}}},
    {true, {.leaf_idx=12}},
    {true, {.leaf_idx=38}},
    {true, {.leaf_idx=72}},
    {false, {.internal={.feature=3, .threshold_idx=29, .left=41, .right=42}}},
    {true, {.leaf_idx=47}},
    {false, {.internal={.feature=2, .threshold_idx=20, .left=43, .right=44}}},
    {true, {.leaf_idx=87}},
    {true, {.leaf_idx=128}},
    {false, {.internal={.feature=6, .threshold_idx=107, .left=46, .right=59}}},
    {false, {.internal={.feature=2, .threshold_idx=2, .left=47, .right=48}}},
    {true, {.leaf_idx=51}},
    {false, {.internal={.feature=1, .threshold_idx=35, .left=49, .right=52}}},
    {false, {.internal={.feature=0, .threshold_idx=99, .left=50, .right=51}}},
    {true, {.leaf_idx=64}},
    {true, {.leaf_idx=105}},
    {false, {.internal={.feature=4, .threshold_idx=78, .left=53, .right=58}}},
    {false, {.internal={.feature=5, .threshold_idx=30, .left=54, .right=55}}},
    {true, {.leaf_idx=77}},
    {false, {.internal={.feature=6, .threshold_idx=65, .left=56, .right=57}}},
    {true, {.leaf_idx=116}},
    {true, {.leaf_idx=137}},
    {true, {.leaf_idx=158}},
    {false, {.internal={.feature=1, .threshold_idx=64, .left=60, .right=61}}},
    {true, {.leaf_idx=140}},
    {true, {.leaf_idx=173}},
    {false, {.internal={.feature=0, .threshold_idx=26, .left=63, .right=68}}},
    {false, {.internal={.feature=6, .threshold_idx=64, .left=64, .right=65}}},
    {true, {.leaf_idx=74}},
    {false, {.internal={.feature=3, .threshold_idx=57, .left=66, .right=67}}},
    {true, {.leaf_idx=111}},
    {true, {.leaf_idx=154}},
    {false, {.internal={.feature=1, .threshold_idx=77, .left=69, .right=76}}},
    {false, {.internal={.feature=5, .threshold_idx=92, .left=70, .right=75}}},
    {false, {.internal={.feature=3, .threshold_idx=87, .left=71, .right=74}}},
    {false, {.internal={.feature=0, .threshold_idx=81, .left=72, .right=73}}},
    {true, {.leaf_idx=98}},
    {true, {.leaf_idx=138}},
    {true, {.leaf_idx=162}},
    {true, {.leaf_idx=174}},
    {false, {.internal={.feature=6, .threshold_idx=90, .left=77, .right=78}}},
    {true, {.leaf_idx=168}},
    {true, {.leaf_idx=178}},
    {false, {.internal={.feature=6, .threshold_idx=86, .left=1, .right=50}}},
    {false, {.internal={.feature=0, .threshold_idx=76, .left=2, .right=33}}},
    {false, {.internal={.feature=2, .threshold_idx=45, .left=3, .right=18}}},
    {false, {.internal={.feature=0, .threshold_idx=7, .left=4, .right=7}}},
    {false, {.internal={.feature=3, .threshold_idx=42, .left=5, .right=6}}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=16}},
    {false, {.internal={.feature=1, .threshold_idx=48, .left=8, .right=11}}},
    {false, {.internal={.feature=6, .threshold_idx=13, .left=9, .right=10}}},
    {true, {.leaf_idx=7}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=5, .threshold_idx=92, .left=12, .right=17}}},
    {false, {.internal={.feature=2, .threshold_idx=6, .left=13, .right=14}}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=6, .threshold_idx=20, .left=15, .right=16}}},
    {true, {.leaf_idx=36}},
    {true, {.leaf_idx=63}},
    {true, {.leaf_idx=81}},
    {false, {.internal={.feature=0, .threshold_idx=8, .left=19, .right=24}}},
    {false, {.internal={.feature=1, .threshold_idx=26, .left=20, .right=21}}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=6, .threshold_idx=12, .left=22, .right=23}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=84}},
    {false, {.internal={.feature=4, .threshold_idx=87, .left=25, .right=30}}},
    {false, {.internal={.feature=5, .threshold_idx=24, .left=26, .right=27}}},
    {true, {.leaf_idx=48}},
    {false, {.internal={.feature=1, .threshold_idx=63, .left=28, .right=29}}},
    {true, {.leaf_idx=73}},
    {true, {.leaf_idx=115}},
    {false, {.internal={.feature=1, .threshold_idx=88, .left=31, .right=32}}},
    {true, {.leaf_idx=109}},
    {true, {.leaf_idx=153}},
    {false, {.internal={.feature=2, .threshold_idx=96, .left=34, .right=47}}},
    {false, {.internal={.feature=4, .threshold_idx=110, .left=35, .right=46}}},
    {false, {.internal={.feature=6, .threshold_idx=23, .left=36, .right=41}}},
    {false, {.internal={.feature=2, .threshold_idx=18, .left=37, .right=38}}},
    {true, {.leaf_idx=31}},
    {false, {.internal={.feature=5, .threshold_idx=74, .left=39, .right=40}}},
    {true, {.leaf_idx=58}},
    {true, {.leaf_idx=94}},
    {false, {.internal={.feature=5, .threshold_idx=22, .left=42, .right=43}}},
    {true, {.leaf_idx=66}},
    {false, {.internal={.feature=2, .threshold_idx=36, .left=44, .right=45}}},
    {true, {.leaf_idx=92}},
    {true, {.leaf_idx=136}},
    {true, {.leaf_idx=148}},
    {false, {.internal={.feature=1, .threshold_idx=72, .left=48, .right=49}}},
    {true, {.leaf_idx=135}},
    {true, {.leaf_idx=171}},
    {false, {.internal={.feature=2, .threshold_idx=75, .left=51, .right=64}}},
    {false, {.internal={.feature=0, .threshold_idx=41, .left=52, .right=57}}},
    {false, {.internal={.feature=1, .threshold_idx=73, .left=53, .right=56}}},
    {false, {.internal={.feature=2, .threshold_idx=35, .left=54, .right=55}}},
    {true, {.leaf_idx=39}},
    {true, {.leaf_idx=97}},
    {true, {.leaf_idx=122}},
    {false, {.internal={.feature=4, .threshold_idx=59, .left=58, .right=61}}},
    {false, {.internal={.feature=3, .threshold_idx=57, .left=59, .right=60}}},
    {true, {.leaf_idx=107}},
    {true, {.leaf_idx=141}},
    {false, {.internal={.feature=1, .threshold_idx=47, .left=62, .right=63}}},
    {true, {.leaf_idx=134}},
    {true, {.leaf_idx=163}},
    {false, {.internal={.feature=0, .threshold_idx=14, .left=65, .right=66}}},
    {true, {.leaf_idx=127}},
    {false, {.internal={.feature=1, .threshold_idx=79, .left=67, .right=70}}},
    {false, {.internal={.feature=4, .threshold_idx=51, .left=68, .right=69}}},
    {true, {.leaf_idx=149}},
    {true, {.leaf_idx=168}},
    {true, {.leaf_idx=176}},
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=28}}},
    {false, {.internal={.feature=0, .threshold_idx=89, .left=2, .right=19}}},
    {false, {.internal={.feature=2, .threshold_idx=55, .left=3, .right=12}}},
    {false, {.internal={.feature=0, .threshold_idx=16, .left=4, .right=7}}},
    {false, {.internal={.feature=2, .threshold_idx=10, .left=5, .right=6}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=1, .threshold_idx=25, .left=8, .right=9}}},
    {true, {.leaf_idx=15}},
    {false, {.internal={.feature=5, .threshold_idx=72, .left=10, .right=11}}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=61}},
    {false, {.internal={.feature=1, .threshold_idx=26, .left=13, .right=14}}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=0, .threshold_idx=15, .left=15, .right=16}}},
    {true, {.leaf_idx=52}},
    {false, {.internal={.feature=3, .threshold_idx=53, .left=17, .right=18}}},
    {true, {.leaf_idx=71}},
    {true, {.leaf_idx=121}},
    {false, {.internal={.feature=3, .threshold_idx=69, .left=20, .right=25}}},
    {false, {.internal={.feature=2, .threshold_idx=68, .left=21, .right=24}}},
    {false, {.internal={.feature=1, .threshold_idx=82, .left=22, .right=23}}},
    {true, {.leaf_idx=45}},
    {true, {.leaf_idx=79}},
    {true, {.leaf_idx=124}},
    {false, {.internal={.feature=4, .threshold_idx=42, .left=26, .right=27}}},
    {true, {.leaf_idx=99}},
    {true, {.leaf_idx=151}},
    {false, {.internal={.feature=2, .threshold_idx=80, .left=29, .right=58}}},
    {false, {.internal={.feature=0, .threshold_idx=42, .left=30, .right=43}}},
    {false, {.internal={.feature=4, .threshold_idx=67, .left=31, .right=38}}},
    {false, {.internal={.feature=1, .threshold_idx=43, .left=32, .right=35}}},
    {false, {.internal={.feature=5, .threshold_idx=63, .left=33, .right=34}}},
    {true, {.leaf_idx=19}},
    {true, {.leaf_idx=42}},
    {false, {.internal={.feature=6, .threshold_idx=95, .left=36, .right=37}}},
    {true, {.leaf_idx=44}},
    {true, {.leaf_idx=100}},
    {false, {.internal={.feature=6, .threshold_idx=102, .left=39, .right=42}}},
    {false, {.internal={.feature=5, .threshold_idx=44, .left=40, .right=41}}},
    {true, {.leaf_idx=46}},
    {true, {.leaf_idx=96}},
    {true, {.leaf_idx=126}},
    {false, {.internal={.feature=6, .threshold_idx=108, .left=44, .right=55}}},
    {false, {.internal={.feature=2, .threshold_idx=4, .left=45, .right=46}}},
    {true, {.leaf_idx=58}},
    {false, {.internal={.feature=1, .threshold_idx=35, .left=47, .right=50}}},
    {false, {.internal={.feature=6, .threshold_idx=76, .left=48, .right=49}}},
    {true, {.leaf_idx=70}},
    {true, {.leaf_idx=102}},
    {false, {.internal={.feature=4, .threshold_idx=73, .left=51, .right=54}}},
    {false, {.internal={.feature=5, .threshold_idx=40, .left=52, .right=53}}},
    {true, {.leaf_idx=83}},
    {true, {.leaf_idx=125}},
    {true, {.leaf_idx=152}},
    {false, {.internal={.feature=1, .threshold_idx=47, .left=56, .right=57}}},
    {true, {.leaf_idx=132}},
    {true, {.leaf_idx=166}},
    {false, {.internal={.feature=0, .threshold_idx=57, .left=59, .right=68}}},
    {false, {.internal={.feature=4, .threshold_idx=46, .left=60, .right=63}}},
    {false, {.internal={.feature=1, .threshold_idx=54, .left=61, .right=62}}},
    {true, {.leaf_idx=69}},
    {true, {.leaf_idx=118}},
    {false, {.internal={.feature=6, .threshold_idx=87, .left=64, .right=67}}},
    {false, {.internal={.feature=5, .threshold_idx=63, .left=65, .right=66}}},
    {true, {.leaf_idx=101}},
    {true, {.leaf_idx=146}},
    {true, {.leaf_idx=159}},
    {false, {.internal={.feature=1, .threshold_idx=100, .left=69, .right=76}}},
    {false, {.internal={.feature=0, .threshold_idx=111, .left=70, .right=75}}},
    {false, {.internal={.feature=4, .threshold_idx=28, .left=71, .right=72}}},
    {true, {.leaf_idx=119}},
    {false, {.internal={.feature=3, .threshold_idx=69, .left=73, .right=74}}},
    {true, {.leaf_idx=143}},
    {true, {.leaf_idx=165}},
    {true, {.leaf_idx=175}},
    {true, {.leaf_idx=177}},
    {false, {.internal={.feature=6, .threshold_idx=68, .left=1, .right=46}}},
    {false, {.internal={.feature=0, .threshold_idx=89, .left=2, .right=33}}},
    {false, {.internal={.feature=2, .threshold_idx=50, .left=3, .right=16}}},
    {false, {.internal={.feature=6, .threshold_idx=3, .left=4, .right=5}}},
    {true, {.leaf_idx=10}},
    {false, {.internal={.feature=1, .threshold_idx=93, .left=6, .right=13}}},
    {false, {.internal={.feature=0, .threshold_idx=14, .left=7, .right=8}}},
    {true, {.leaf_idx=8}},
    {false, {.internal={.feature=4, .threshold_idx=75, .left=9, .right=12}}},
    {false, {.internal={.feature=3, .threshold_idx=40, .left=10, .right=11}}},
    {true, {.leaf_idx=20}},
    {true, {.leaf_idx=37}},
    {true, {.leaf_idx=65}},
    {false, {.internal={.feature=4, .threshold_idx=44, .left=14, .right=15}}},
    {true, {.leaf_idx=56}},
    {true, {.leaf_idx=85}},
    {false, {.internal={.feature=1, .threshold_idx=32, .left=17, .right=22}}},
    {false, {.internal={.feature=4, .threshold_idx=35, .left=18, .right=19}}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=0, .threshold_idx=28, .left=20, .right=21}}},
    {true, {.leaf_idx=41}},
    {true, {.leaf_idx=80}},
    {false, {.internal={.feature=4, .threshold_idx=87, .left=23, .right=30}}},
    {false, {.internal={.feature=0, .threshold_idx=21, .left=24, .right=27}}},
    {false, {.internal={.feature=5, .threshold_idx=47, .left=25, .right=26}}},
    {true, {.leaf_idx=40}},
    {true, {.leaf_idx=67}},
    {false, {.internal={.feature=5, .threshold_idx=27, .left=28, .right=29}}},
    {true, {.leaf_idx=71}},
    {true, {.leaf_idx=113}},
    {false, {.internal={.feature=6, .threshold_idx=19, .left=31, .right=32}}},
    {true, {.leaf_idx=95}},
    {true, {.leaf_idx=142}},
    {false, {.internal={.feature=2, .threshold_idx=67, .left=34, .right=41}}},
    {false, {.internal={.feature=1, .threshold_idx=76, .left=35, .right=38}}},
    {false, {.internal={.feature=5, .threshold_idx=38, .left=36, .right=37}}},
    {true, {.leaf_idx=53}},
    {true, {.leaf_idx=88}},
    {false, {.internal={.feature=3, .threshold_idx=45, .left=39, .right=40}}},
    {true, {.leaf_idx=86}},
    {true, {.leaf_idx=130}},
    {false, {.internal={.feature=1, .threshold_idx=85, .left=42, .right=45}}},
    {false, {.internal={.feature=4, .threshold_idx=33, .left=43, .right=44}}},
    {true, {.leaf_idx=93}},
    {true, {.leaf_idx=144}},
    {true, {.leaf_idx=160}},
    {false, {.internal={.feature=2, .threshold_idx=80, .left=47, .right=66}}},
    {false, {.internal={.feature=4, .threshold_idx=72, .left=48, .right=59}}},
    {false, {.internal={.feature=0, .threshold_idx=60, .left=49, .right=54}}},
    {false, {.internal={.feature=5, .threshold_idx=72, .left=50, .right=53}}},
    {false, {.internal={.feature=0, .threshold_idx=9, .left=51, .right=52}}},
    {true, {.leaf_idx=27}},
    {true, {.leaf_idx=62}},
    {true, {.leaf_idx=104}},
    {false, {.internal={.feature=6, .threshold_idx=105, .left=55, .right=58}}},
    {false, {.internal={.feature=5, .threshold_idx=66, .left=56, .right=57}}},
    {true, {.leaf_idx=82}},
    {true, {.leaf_idx=121}},
    {true, {.leaf_idx=147}},
    {false, {.internal={.feature=1, .threshold_idx=39, .left=60, .right=63}}},
    {false, {.internal={.feature=0, .threshold_idx=34, .left=61, .right=62}}},
    {true, {.leaf_idx=76}},
    {true, {.leaf_idx=123}},
    {false, {.internal={.feature=6, .threshold_idx=109, .left=64, .right=65}}},
    {true, {.leaf_idx=132}},
    {true, {.leaf_idx=161}},
    {false, {.internal={.feature=1, .threshold_idx=97, .left=67, .right=74}}},
    {false, {.internal={.feature=4, .threshold_idx=101, .left=68, .right=73}}},
    {false, {.internal={.feature=2, .threshold_idx=112, .left=69, .right=72}}},
    {false, {.internal={.feature=0, .threshold_idx=58, .left=70, .right=71}}},
    {true, {.leaf_idx=108}},
    {true, {.leaf_idx=133}},
    {true, {.leaf_idx=156}},
    {true, {.leaf_idx=164}},
    {true, {.leaf_idx=172}}
};


/* Tree metadata */
static const OptTree TREES[N_TREES] = {
    {0, 67},
    {67, 79},
    {146, 71},
    {217, 77},
    {294, 75}
};


/* Tree traversal function */
static inline float traverse_tree(int tree_id, const float* x) {
    const OptTree* tree = &TREES[tree_id];
    uint32_t node_idx = tree->start_idx;

    while (node_idx < tree->start_idx + tree->node_count) {
        const OptNode* node = &NODES[node_idx];

        if (node->is_leaf) {
            return SHARED_LEAVES[node->u.leaf_idx];
        }

        float threshold = SHARED_THRESHOLDS[node->u.internal.threshold_idx];

        if (x[node->u.internal.feature] < threshold) {
            node_idx = tree->start_idx + node->u.internal.left;
        } else {
            node_idx = tree->start_idx + node->u.internal.right;
        }
    }

    return 0.0f; /* Should never reach here */
}

float predict(const float* x) {
    float sum = 0.000000f;
    for (int i = 0; i < N_TREES; i++) {
        sum += traverse_tree(i, x);
    }
    return sum;
}

/*
// Memory breakdown:
// - Nodes: 2214 bytes (369 x 6)
// - Thresholds: 452 bytes (N_THRESHOLDS x 4)
// - Leaves: 720 bytes (N_LEAVES x 4)
// - Metadata: 30 bytes (N_TREES x (4 + 2))
// - Total: 3416 bytes
// Alignment: 4 bytes
// Feature type: uint8_t
// Threshold index type: uint8_t
// Node index type: uint8_t
// Leaf index type: uint8_t
*/


#ifdef __cplusplus
}
#endif

#endif /* EMBEDDED_TREES_MINIMAL_H */
