/*
 * Ultra-Minimal Memory Embedded Tree Ensemble Model
 * 
 * Model Metadata:
 *   - Number of trees: 5
 *   - Number of features: 10
 *   - Number of classes: 1
 *   - Task type: BINARY_CLASSIFICATION
 *   - Base score: 0.000000
 * 
 * Optimization Configuration:
 *   - Threshold precision: 2 decimal places
 *   - Leaf precision: 2 decimal places
 *   - Packed structs: Yes
 *   - Node size: 6 bytes
 *   - Total nodes: 301
 * 
 * Memory Usage:
 *   - Original: 7,264 bytes
 *   - Optimized: 2,308 bytes
 *   - Compression: 3.15x
 *   - Threshold deduplication: 148 -> 82
 *   - Leaf deduplication: 153 -> 36
 * 
 * IMPORTANT: This file is automatically generated. Do not edit manually.
 */

#ifndef EMBEDDED_TREES_MINIMAL_H
#define EMBEDDED_TREES_MINIMAL_H


#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif


/* Model constants */
#define N_TREES 5
#define N_FEATURES 10
#define N_CLASSES 1
#define N_THRESHOLDS 82
#define N_LEAVES 36
#define TASK_TYPE BINARY_CLASSIFICATION
#define BASE_SCORE 0.000000f
#define THRESHOLD_PRECISION 2
#define LEAF_PRECISION 2
#define PACK_STRUCTS 1
#define NODE_SIZE 6
#define TOTAL_NODES 301
#define ORIGINAL_MEMORY 7264
#define OPTIMIZED_MEMORY 2308
#define COMPRESSION_RATIO 3.15
#define ORIGINAL_THRESHOLDS 148
#define UNIQUE_THRESHOLDS 82
#define ORIGINAL_LEAVES 153
#define UNIQUE_LEAVES 36


/* Optimized tree node structure */
#pragma pack(push, 1)
typedef struct {
    uint8_t is_leaf : 1;  /* Bitfield for minimal bool size */
    union {
        struct {
            uint8_t feature;
            uint8_t threshold_idx;
            uint8_t left;
            uint8_t right;
        } internal;
        uint8_t leaf_idx;
    } u;
} OptNode;
#pragma pack(pop)

typedef struct {
    uint32_t start_idx;  /* Start index in global node array */
    uint16_t node_count;
} OptTree;


/* Shared data arrays for deduplication */
static const float SHARED_THRESHOLDS[N_THRESHOLDS] = { -1.56f, -1.53f, -1.52f, -1.41f, -1.38f, -1.28f, -1.22f, -1.06f, -0.97f, -0.96f, -0.92f, -0.91f, -0.90f, -0.83f, -0.81f, -0.78f, -0.77f, -0.71f, -0.69f, -0.68f, -0.67f, -0.66f, -0.64f, -0.62f, -0.58f, -0.57f, -0.56f, -0.54f, -0.53f, -0.50f, -0.48f, -0.47f, -0.44f, -0.43f, -0.42f, -0.38f, -0.37f, -0.34f, -0.33f, -0.26f, -0.25f, -0.22f, -0.20f, -0.18f, -0.14f, -0.12f, -0.09f, -0.08f, -0.07f, -0.06f, -0.04f, -0.02f, -0.01f, -0.00f, 0.01f, 0.05f, 0.06f, 0.07f, 0.09f, 0.14f, 0.18f, 0.19f, 0.26f, 0.28f, 0.39f, 0.41f, 0.44f, 0.50f, 0.52f, 0.60f, 0.65f, 0.68f, 0.71f, 0.78f, 0.86f, 0.88f, 1.06f, 1.14f, 1.15f, 1.35f, 1.39f, 1.42f };
static const float SHARED_LEAVES[N_LEAVES] = { -0.20f, -0.19f, -0.18f, -0.17f, -0.16f, -0.15f, -0.14f, -0.13f, -0.12f, -0.11f, -0.10f, -0.09f, -0.08f, -0.07f, -0.06f, -0.05f, -0.03f, -0.02f, -0.01f, -0.00f, 0.03f, 0.04f, 0.05f, 0.06f, 0.07f, 0.08f, 0.09f, 0.11f, 0.12f, 0.13f, 0.14f, 0.15f, 0.16f, 0.17f, 0.18f, 0.20f };


/* Single global node array */
static const OptNode NODES[TOTAL_NODES] = {
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=30}}},
    {false, {.internal={.feature=8, .threshold_idx=64, .left=2, .right=23}}},
    {false, {.internal={.feature=6, .threshold_idx=21, .left=3, .right=20}}},
    {false, {.internal={.feature=1, .threshold_idx=70, .left=4, .right=15}}},
    {false, {.internal={.feature=9, .threshold_idx=78, .left=5, .right=14}}},
    {false, {.internal={.feature=8, .threshold_idx=6, .left=6, .right=9}}},
    {false, {.internal={.feature=2, .threshold_idx=80, .left=7, .right=8}}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=0}},
    {false, {.internal={.feature=1, .threshold_idx=62, .left=10, .right=13}}},
    {false, {.internal={.feature=6, .threshold_idx=10, .left=11, .right=12}}},
    {true, {.leaf_idx=0}},
    {true, {.leaf_idx=0}},
    {true, {.leaf_idx=2}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=9, .threshold_idx=57, .left=16, .right=17}}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=1, .threshold_idx=76, .left=18, .right=19}}},
    {true, {.leaf_idx=19}},
    {true, {.leaf_idx=8}},
    {false, {.internal={.feature=8, .threshold_idx=16, .left=21, .right=22}}},
    {true, {.leaf_idx=9}},
    {true, {.leaf_idx=23}},
    {false, {.internal={.feature=8, .threshold_idx=75, .left=24, .right=27}}},
    {false, {.internal={.feature=8, .threshold_idx=72, .left=25, .right=26}}},
    {true, {.leaf_idx=0}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=0, .threshold_idx=52, .left=28, .right=29}}},
    {true, {.leaf_idx=0}},
    {true, {.leaf_idx=0}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=31, .right=38}}},
    {false, {.internal={.feature=8, .threshold_idx=46, .left=32, .right=35}}},
    {false, {.internal={.feature=8, .threshold_idx=26, .left=33, .right=34}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=0, .threshold_idx=24, .left=36, .right=37}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=35}},
    {false, {.internal={.feature=8, .threshold_idx=36, .left=39, .right=48}}},
    {false, {.internal={.feature=8, .threshold_idx=13, .left=40, .right=43}}},
    {false, {.internal={.feature=5, .threshold_idx=35, .left=41, .right=42}}},
    {true, {.leaf_idx=30}},
    {true, {.leaf_idx=35}},
    {false, {.internal={.feature=8, .threshold_idx=25, .left=44, .right=47}}},
    {false, {.internal={.feature=5, .threshold_idx=69, .left=45, .right=46}}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=0}},
    {true, {.leaf_idx=17}},
    {false, {.internal={.feature=2, .threshold_idx=50, .left=49, .right=50}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=30}}},
    {false, {.internal={.feature=8, .threshold_idx=64, .left=2, .right=23}}},
    {false, {.internal={.feature=6, .threshold_idx=7, .left=3, .right=14}}},
    {false, {.internal={.feature=8, .threshold_idx=1, .left=4, .right=5}}},
    {true, {.leaf_idx=11}},
    {false, {.internal={.feature=9, .threshold_idx=75, .left=6, .right=13}}},
    {false, {.internal={.feature=8, .threshold_idx=14, .left=7, .right=12}}},
    {false, {.internal={.feature=9, .threshold_idx=61, .left=8, .right=11}}},
    {false, {.internal={.feature=8, .threshold_idx=6, .left=9, .right=10}}},
    {true, {.leaf_idx=2}},
    {true, {.leaf_idx=2}},
    {true, {.leaf_idx=1}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=10}},
    {false, {.internal={.feature=1, .threshold_idx=74, .left=15, .right=22}}},
    {false, {.internal={.feature=8, .threshold_idx=19, .left=16, .right=21}}},
    {false, {.internal={.feature=8, .threshold_idx=9, .left=17, .right=18}}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=0, .threshold_idx=70, .left=19, .right=20}}},
    {true, {.leaf_idx=1}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=15}},
    {true, {.leaf_idx=22}},
    {false, {.internal={.feature=8, .threshold_idx=75, .left=24, .right=27}}},
    {false, {.internal={.feature=8, .threshold_idx=72, .left=25, .right=26}}},
    {true, {.leaf_idx=2}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=0, .threshold_idx=53, .left=28, .right=29}}},
    {true, {.leaf_idx=2}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=31, .right=38}}},
    {false, {.internal={.feature=8, .threshold_idx=46, .left=32, .right=35}}},
    {false, {.internal={.feature=8, .threshold_idx=26, .left=33, .right=34}}},
    {true, {.leaf_idx=34}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=0, .threshold_idx=23, .left=36, .right=37}}},
    {true, {.leaf_idx=34}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=8, .threshold_idx=36, .left=39, .right=50}}},
    {false, {.internal={.feature=8, .threshold_idx=13, .left=40, .right=45}}},
    {false, {.internal={.feature=5, .threshold_idx=35, .left=41, .right=42}}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=1, .threshold_idx=39, .left=43, .right=44}}},
    {true, {.leaf_idx=34}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=4, .threshold_idx=30, .left=46, .right=47}}},
    {true, {.leaf_idx=19}},
    {false, {.internal={.feature=5, .threshold_idx=30, .left=48, .right=49}}},
    {true, {.leaf_idx=15}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=6, .threshold_idx=55, .left=51, .right=52}}},
    {true, {.leaf_idx=28}},
    {false, {.internal={.feature=6, .threshold_idx=63, .left=53, .right=54}}},
    {true, {.leaf_idx=34}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=34}}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=2, .right=29}}},
    {false, {.internal={.feature=1, .threshold_idx=70, .left=3, .right=22}}},
    {false, {.internal={.feature=8, .threshold_idx=6, .left=4, .right=7}}},
    {false, {.internal={.feature=2, .threshold_idx=79, .left=5, .right=6}}},
    {true, {.leaf_idx=12}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=5, .threshold_idx=4, .left=8, .right=9}}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=3, .threshold_idx=3, .left=10, .right=11}}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=8, .threshold_idx=66, .left=12, .right=17}}},
    {false, {.internal={.feature=8, .threshold_idx=15, .left=13, .right=16}}},
    {false, {.internal={.feature=6, .threshold_idx=8, .left=14, .right=15}}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=8, .threshold_idx=75, .left=18, .right=19}}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=1, .threshold_idx=44, .left=20, .right=21}}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=9, .threshold_idx=57, .left=23, .right=26}}},
    {false, {.internal={.feature=3, .threshold_idx=68, .left=24, .right=25}}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=9}},
    {false, {.internal={.feature=8, .threshold_idx=53, .left=27, .right=28}}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=2, .threshold_idx=60, .left=30, .right=31}}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=8, .threshold_idx=16, .left=32, .right=33}}},
    {true, {.leaf_idx=11}},
    {true, {.leaf_idx=20}},
    {false, {.internal={.feature=2, .threshold_idx=42, .left=35, .right=48}}},
    {false, {.internal={.feature=8, .threshold_idx=46, .left=36, .right=45}}},
    {false, {.internal={.feature=8, .threshold_idx=22, .left=37, .right=42}}},
    {false, {.internal={.feature=2, .threshold_idx=32, .left=38, .right=41}}},
    {false, {.internal={.feature=0, .threshold_idx=31, .left=39, .right=40}}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=5, .threshold_idx=40, .left=43, .right=44}}},
    {true, {.leaf_idx=27}},
    {true, {.leaf_idx=15}},
    {false, {.internal={.feature=2, .threshold_idx=37, .left=46, .right=47}}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=33}},
    {false, {.internal={.feature=8, .threshold_idx=12, .left=49, .right=52}}},
    {false, {.internal={.feature=8, .threshold_idx=1, .left=50, .right=51}}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=8, .threshold_idx=25, .left=53, .right=56}}},
    {false, {.internal={.feature=4, .threshold_idx=47, .left=54, .right=55}}},
    {true, {.leaf_idx=11}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=2, .threshold_idx=54, .left=57, .right=58}}},
    {true, {.leaf_idx=24}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=6, .threshold_idx=42, .left=1, .right=40}}},
    {false, {.internal={.feature=6, .threshold_idx=28, .left=2, .right=35}}},
    {false, {.internal={.feature=8, .threshold_idx=64, .left=3, .right=20}}},
    {false, {.internal={.feature=6, .threshold_idx=7, .left=4, .right=15}}},
    {false, {.internal={.feature=8, .threshold_idx=1, .left=5, .right=6}}},
    {true, {.leaf_idx=13}},
    {false, {.internal={.feature=9, .threshold_idx=75, .left=7, .right=14}}},
    {false, {.internal={.feature=8, .threshold_idx=14, .left=8, .right=13}}},
    {false, {.internal={.feature=9, .threshold_idx=60, .left=9, .right=12}}},
    {false, {.internal={.feature=8, .threshold_idx=6, .left=10, .right=11}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=12}},
    {false, {.internal={.feature=8, .threshold_idx=9, .left=16, .right=17}}},
    {true, {.leaf_idx=18}},
    {false, {.internal={.feature=8, .threshold_idx=19, .left=18, .right=19}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=13}},
    {false, {.internal={.feature=7, .threshold_idx=5, .left=21, .right=22}}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=7, .threshold_idx=81, .left=23, .right=34}}},
    {false, {.internal={.feature=8, .threshold_idx=75, .left=24, .right=27}}},
    {false, {.internal={.feature=5, .threshold_idx=50, .left=25, .right=26}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=28, .right=33}}},
    {false, {.internal={.feature=5, .threshold_idx=24, .left=29, .right=30}}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=3, .threshold_idx=51, .left=31, .right=32}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=4, .threshold_idx=37, .left=36, .right=37}}},
    {true, {.leaf_idx=23}},
    {false, {.internal={.feature=3, .threshold_idx=56, .left=38, .right=39}}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=16}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=41, .right=50}}},
    {false, {.internal={.feature=8, .threshold_idx=46, .left=42, .right=49}}},
    {false, {.internal={.feature=8, .threshold_idx=26, .left=43, .right=48}}},
    {false, {.internal={.feature=1, .threshold_idx=15, .left=44, .right=45}}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=2, .threshold_idx=20, .left=46, .right=47}}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=24}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=8, .threshold_idx=36, .left=51, .right=62}}},
    {false, {.internal={.feature=8, .threshold_idx=14, .left=52, .right=57}}},
    {false, {.internal={.feature=5, .threshold_idx=37, .left=53, .right=54}}},
    {true, {.leaf_idx=28}},
    {false, {.internal={.feature=8, .threshold_idx=2, .left=55, .right=56}}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=5, .threshold_idx=27, .left=58, .right=59}}},
    {true, {.leaf_idx=18}},
    {false, {.internal={.feature=9, .threshold_idx=49, .left=60, .right=61}}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=7, .threshold_idx=73, .left=63, .right=66}}},
    {false, {.internal={.feature=2, .threshold_idx=42, .left=64, .right=65}}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=28}},
    {false, {.internal={.feature=6, .threshold_idx=33, .left=1, .right=36}}},
    {false, {.internal={.feature=8, .threshold_idx=64, .left=2, .right=23}}},
    {false, {.internal={.feature=6, .threshold_idx=7, .left=3, .right=14}}},
    {false, {.internal={.feature=7, .threshold_idx=40, .left=4, .right=9}}},
    {false, {.internal={.feature=7, .threshold_idx=6, .left=5, .right=6}}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=9, .threshold_idx=61, .left=7, .right=8}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=1, .threshold_idx=70, .left=10, .right=13}}},
    {false, {.internal={.feature=9, .threshold_idx=48, .left=11, .right=12}}},
    {true, {.leaf_idx=9}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=1, .threshold_idx=74, .left=15, .right=22}}},
    {false, {.internal={.feature=3, .threshold_idx=10, .left=16, .right=17}}},
    {true, {.leaf_idx=16}},
    {false, {.internal={.feature=1, .threshold_idx=17, .left=18, .right=19}}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=1, .threshold_idx=59, .left=20, .right=21}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=9}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=6, .threshold_idx=0, .left=24, .right=25}}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=5, .threshold_idx=76, .left=26, .right=35}}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=27, .right=34}}},
    {false, {.internal={.feature=8, .threshold_idx=77, .left=28, .right=31}}},
    {false, {.internal={.feature=8, .threshold_idx=72, .left=29, .right=30}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=1, .threshold_idx=43, .left=32, .right=33}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=2, .threshold_idx=45, .left=37, .right=56}}},
    {false, {.internal={.feature=8, .threshold_idx=46, .left=38, .right=49}}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=39, .right=46}}},
    {false, {.internal={.feature=3, .threshold_idx=71, .left=40, .right=45}}},
    {false, {.internal={.feature=5, .threshold_idx=29, .left=41, .right=42}}},
    {true, {.leaf_idx=32}},
    {false, {.internal={.feature=9, .threshold_idx=30, .left=43, .right=44}}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=5, .threshold_idx=58, .left=47, .right=48}}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=11}},
    {false, {.internal={.feature=2, .threshold_idx=41, .left=50, .right=55}}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=51, .right=54}}},
    {false, {.internal={.feature=0, .threshold_idx=5, .left=52, .right=53}}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=31}},
    {false, {.internal={.feature=8, .threshold_idx=11, .left=57, .right=60}}},
    {false, {.internal={.feature=8, .threshold_idx=0, .left=58, .right=59}}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=8, .threshold_idx=22, .left=61, .right=64}}},
    {false, {.internal={.feature=4, .threshold_idx=38, .left=62, .right=63}}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=4, .threshold_idx=35, .left=65, .right=66}}},
    {true, {.leaf_idx=31}},
    {false, {.internal={.feature=9, .threshold_idx=65, .left=67, .right=68}}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=27}}
};


/* Tree metadata */
static const OptTree TREES[N_TREES] = {
    {0, 51},
    {51, 55},
    {106, 59},
    {165, 67},
    {232, 69}
};


/* Tree traversal function */
static inline float traverse_tree(int tree_id, const float* x) {
    const OptTree* tree = &TREES[tree_id];
    uint32_t node_idx = tree->start_idx;

    while (node_idx < tree->start_idx + tree->node_count) {
        const OptNode* node = &NODES[node_idx];

        if (node->is_leaf) {
            return SHARED_LEAVES[node->u.leaf_idx];
        }

        float threshold = SHARED_THRESHOLDS[node->u.internal.threshold_idx];

        if (x[node->u.internal.feature] < threshold) {
            node_idx = tree->start_idx + node->u.internal.left;
        } else {
            node_idx = tree->start_idx + node->u.internal.right;
        }
    }

    return 0.0f; /* Should never reach here */
}

float predict(const float* x) {
    float logit = 0.000000f;
    for (int i = 0; i < N_TREES; i++) {
        logit += traverse_tree(i, x);
    }
    return 1.0f / (1.0f + expf(-logit));
}

/*
// Memory breakdown:
// - Nodes: 1806 bytes (301 x 6)
// - Thresholds: 328 bytes (N_THRESHOLDS x 4)
// - Leaves: 144 bytes (N_LEAVES x 4)
// - Metadata: 30 bytes (N_TREES x (4 + 2))
// - Total: 2308 bytes
// Alignment: 4 bytes
// Feature type: uint8_t
// Threshold index type: uint8_t
// Node index type: uint8_t
// Leaf index type: uint8_t
*/


#ifdef __cplusplus
}
#endif

#endif /* EMBEDDED_TREES_MINIMAL_H */
