/*
 * Ultra-Minimal Memory Embedded Tree Ensemble Model
 * 
 * Model Metadata:
 *   - Number of trees: 5
 *   - Number of features: 10
 *   - Number of classes: 1
 *   - Task type: BINARY_CLASSIFICATION
 *   - Base score: 0.499000
 * 
 * Optimization Configuration:
 *   - Threshold precision: 2 decimal places
 *   - Leaf precision: 2 decimal places
 *   - Packed structs: Yes
 *   - Node size: 6 bytes
 *   - Total nodes: 335
 * 
 * Memory Usage:
 *   - Original: 8,080 bytes
 *   - Optimized: 2,512 bytes
 *   - Compression: 3.22x
 *   - Threshold deduplication: 165 -> 79
 *   - Leaf deduplication: 170 -> 39
 * 
 * IMPORTANT: This file is automatically generated. Do not edit manually.
 */

#ifndef EMBEDDED_TREES_MINIMAL_H
#define EMBEDDED_TREES_MINIMAL_H


#include <stdint.h>
#include <stdbool.h>
#include <math.h>

#ifdef __cplusplus
extern "C" {
#endif


/* Model constants */
#define N_TREES 5
#define N_FEATURES 10
#define N_CLASSES 1
#define N_THRESHOLDS 79
#define N_LEAVES 39
#define TASK_TYPE BINARY_CLASSIFICATION
#define BASE_SCORE 0.499000f
#define THRESHOLD_PRECISION 2
#define LEAF_PRECISION 2
#define PACK_STRUCTS 1
#define NODE_SIZE 6
#define TOTAL_NODES 335
#define ORIGINAL_MEMORY 8080
#define OPTIMIZED_MEMORY 2512
#define COMPRESSION_RATIO 3.22
#define ORIGINAL_THRESHOLDS 165
#define UNIQUE_THRESHOLDS 79
#define ORIGINAL_LEAVES 170
#define UNIQUE_LEAVES 39


/* Optimized tree node structure */
#pragma pack(push, 1)
typedef struct {
    uint8_t is_leaf : 1;  /* Bitfield for minimal bool size */
    union {
        struct {
            uint8_t feature;
            uint8_t threshold_idx;
            uint8_t left;
            uint8_t right;
        } internal;
        uint8_t leaf_idx;
    } u;
} OptNode;
#pragma pack(pop)

typedef struct {
    uint32_t start_idx;  /* Start index in global node array */
    uint16_t node_count;
} OptTree;


/* Shared data arrays for deduplication */
static const float SHARED_THRESHOLDS[N_THRESHOLDS] = { -2.76f, -2.22f, -1.94f, -1.89f, -1.84f, -1.76f, -1.51f, -1.50f, -1.40f, -1.34f, -1.32f, -1.31f, -1.21f, -0.98f, -0.92f, -0.91f, -0.85f, -0.84f, -0.82f, -0.81f, -0.78f, -0.74f, -0.73f, -0.69f, -0.67f, -0.63f, -0.62f, -0.58f, -0.57f, -0.55f, -0.53f, -0.46f, -0.44f, -0.42f, -0.41f, -0.37f, -0.36f, -0.34f, -0.32f, -0.27f, -0.22f, -0.20f, -0.17f, -0.14f, -0.11f, -0.08f, -0.06f, -0.04f, 0.02f, 0.04f, 0.05f, 0.08f, 0.17f, 0.21f, 0.29f, 0.32f, 0.33f, 0.35f, 0.41f, 0.42f, 0.43f, 0.48f, 0.50f, 0.53f, 0.54f, 0.59f, 0.61f, 0.66f, 0.67f, 0.69f, 0.87f, 0.93f, 0.96f, 1.01f, 1.06f, 1.19f, 1.47f, 1.59f, 2.40f };
static const float SHARED_LEAVES[N_LEAVES] = { -0.19f, -0.18f, -0.17f, -0.16f, -0.15f, -0.14f, -0.13f, -0.12f, -0.11f, -0.10f, -0.09f, -0.08f, -0.07f, -0.06f, -0.05f, -0.04f, -0.03f, -0.02f, -0.01f, 0.00f, 0.01f, 0.02f, 0.03f, 0.04f, 0.05f, 0.06f, 0.07f, 0.08f, 0.09f, 0.10f, 0.11f, 0.12f, 0.13f, 0.14f, 0.15f, 0.16f, 0.17f, 0.18f, 0.19f };


/* Single global node array */
static const OptNode NODES[TOTAL_NODES] = {
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=2}}},
    {false, {.internal={.feature=8, .threshold_idx=4, .left=3, .right=4}}},
    {false, {.internal={.feature=2, .threshold_idx=41, .left=5, .right=6}}},
    {true, {.leaf_idx=27}},
    {false, {.internal={.feature=6, .threshold_idx=24, .left=7, .right=8}}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=9, .right=10}}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=11, .right=12}}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=13, .right=14}}},
    {false, {.internal={.feature=2, .threshold_idx=52, .left=15, .right=16}}},
    {true, {.leaf_idx=38}},
    {false, {.internal={.feature=6, .threshold_idx=68, .left=17, .right=18}}},
    {false, {.internal={.feature=5, .threshold_idx=26, .left=19, .right=20}}},
    {false, {.internal={.feature=8, .threshold_idx=32, .left=21, .right=22}}},
    {true, {.leaf_idx=0}},
    {false, {.internal={.feature=9, .threshold_idx=54, .left=23, .right=24}}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=8, .threshold_idx=20, .left=25, .right=26}}},
    {true, {.leaf_idx=37}},
    {false, {.internal={.feature=8, .threshold_idx=22, .left=27, .right=28}}},
    {false, {.internal={.feature=1, .threshold_idx=27, .left=29, .right=30}}},
    {true, {.leaf_idx=37}},
    {false, {.internal={.feature=4, .threshold_idx=2, .left=31, .right=32}}},
    {false, {.internal={.feature=8, .threshold_idx=60, .left=33, .right=34}}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=35, .right=36}}},
    {false, {.internal={.feature=7, .threshold_idx=36, .left=37, .right=38}}},
    {false, {.internal={.feature=2, .threshold_idx=63, .left=39, .right=40}}},
    {false, {.internal={.feature=3, .threshold_idx=30, .left=41, .right=42}}},
    {true, {.leaf_idx=36}},
    {false, {.internal={.feature=0, .threshold_idx=40, .left=43, .right=44}}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=1, .threshold_idx=71, .left=45, .right=46}}},
    {false, {.internal={.feature=3, .threshold_idx=76, .left=47, .right=48}}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=1}},
    {true, {.leaf_idx=12}},
    {true, {.leaf_idx=4}},
    {false, {.internal={.feature=7, .threshold_idx=46, .left=49, .right=50}}},
    {false, {.internal={.feature=1, .threshold_idx=62, .left=51, .right=52}}},
    {true, {.leaf_idx=19}},
    {false, {.internal={.feature=3, .threshold_idx=11, .left=53, .right=54}}},
    {false, {.internal={.feature=0, .threshold_idx=56, .left=55, .right=56}}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=2, .threshold_idx=37, .left=57, .right=58}}},
    {false, {.internal={.feature=8, .threshold_idx=28, .left=59, .right=60}}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=36}},
    {true, {.leaf_idx=23}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=8, .threshold_idx=9, .left=61, .right=62}}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=17}},
    {true, {.leaf_idx=26}},
    {true, {.leaf_idx=7}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=17}},
    {true, {.leaf_idx=1}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=19}},
    {false, {.internal={.feature=4, .threshold_idx=45, .left=63, .right=64}}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=6, .threshold_idx=37, .left=1, .right=2}}},
    {false, {.internal={.feature=8, .threshold_idx=4, .left=3, .right=4}}},
    {false, {.internal={.feature=2, .threshold_idx=41, .left=5, .right=6}}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=6, .threshold_idx=24, .left=7, .right=8}}},
    {false, {.internal={.feature=8, .threshold_idx=45, .left=9, .right=10}}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=11, .right=12}}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=13, .right=14}}},
    {false, {.internal={.feature=2, .threshold_idx=52, .left=15, .right=16}}},
    {false, {.internal={.feature=8, .threshold_idx=23, .left=17, .right=18}}},
    {true, {.leaf_idx=37}},
    {false, {.internal={.feature=5, .threshold_idx=26, .left=19, .right=20}}},
    {false, {.internal={.feature=8, .threshold_idx=32, .left=21, .right=22}}},
    {false, {.internal={.feature=7, .threshold_idx=1, .left=23, .right=24}}},
    {false, {.internal={.feature=9, .threshold_idx=54, .left=25, .right=26}}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=8, .threshold_idx=20, .left=27, .right=28}}},
    {true, {.leaf_idx=37}},
    {false, {.internal={.feature=5, .threshold_idx=51, .left=29, .right=30}}},
    {false, {.internal={.feature=2, .threshold_idx=48, .left=31, .right=32}}},
    {true, {.leaf_idx=36}},
    {false, {.internal={.feature=4, .threshold_idx=21, .left=33, .right=34}}},
    {false, {.internal={.feature=8, .threshold_idx=60, .left=35, .right=36}}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=2}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=37, .right=38}}},
    {false, {.internal={.feature=7, .threshold_idx=36, .left=39, .right=40}}},
    {false, {.internal={.feature=3, .threshold_idx=14, .left=41, .right=42}}},
    {false, {.internal={.feature=3, .threshold_idx=30, .left=43, .right=44}}},
    {false, {.internal={.feature=9, .threshold_idx=42, .left=45, .right=46}}},
    {false, {.internal={.feature=3, .threshold_idx=22, .left=47, .right=48}}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=8, .threshold_idx=25, .left=49, .right=50}}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=3, .threshold_idx=76, .left=51, .right=52}}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=3}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=7, .threshold_idx=46, .left=53, .right=54}}},
    {true, {.leaf_idx=20}},
    {false, {.internal={.feature=4, .threshold_idx=66, .left=55, .right=56}}},
    {false, {.internal={.feature=3, .threshold_idx=11, .left=57, .right=58}}},
    {false, {.internal={.feature=3, .threshold_idx=59, .left=59, .right=60}}},
    {false, {.internal={.feature=7, .threshold_idx=53, .left=61, .right=62}}},
    {false, {.internal={.feature=7, .threshold_idx=39, .left=63, .right=64}}},
    {true, {.leaf_idx=22}},
    {false, {.internal={.feature=9, .threshold_idx=46, .left=65, .right=66}}},
    {false, {.internal={.feature=5, .threshold_idx=65, .left=67, .right=68}}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=23}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=3, .threshold_idx=17, .left=69, .right=70}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=17}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=31}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=12}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=7}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=7, .threshold_idx=62, .left=71, .right=72}}},
    {true, {.leaf_idx=10}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=6, .threshold_idx=38, .left=1, .right=2}}},
    {false, {.internal={.feature=8, .threshold_idx=4, .left=3, .right=4}}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=5, .right=6}}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=6, .threshold_idx=24, .left=7, .right=8}}},
    {false, {.internal={.feature=5, .threshold_idx=78, .left=9, .right=10}}},
    {false, {.internal={.feature=8, .threshold_idx=35, .left=11, .right=12}}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=13, .right=14}}},
    {false, {.internal={.feature=0, .threshold_idx=50, .left=15, .right=16}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=24}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=17, .right=18}}},
    {false, {.internal={.feature=6, .threshold_idx=41, .left=19, .right=20}}},
    {true, {.leaf_idx=3}},
    {false, {.internal={.feature=9, .threshold_idx=54, .left=21, .right=22}}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=8, .threshold_idx=20, .left=23, .right=24}}},
    {false, {.internal={.feature=6, .threshold_idx=48, .left=25, .right=26}}},
    {false, {.internal={.feature=6, .threshold_idx=39, .left=27, .right=28}}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=29, .right=30}}},
    {false, {.internal={.feature=8, .threshold_idx=57, .left=31, .right=32}}},
    {false, {.internal={.feature=3, .threshold_idx=14, .left=33, .right=34}}},
    {false, {.internal={.feature=1, .threshold_idx=35, .left=35, .right=36}}},
    {false, {.internal={.feature=1, .threshold_idx=35, .left=37, .right=38}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=27}},
    {false, {.internal={.feature=9, .threshold_idx=13, .left=39, .right=40}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=13}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=41, .right=42}}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=20}},
    {false, {.internal={.feature=7, .threshold_idx=6, .left=43, .right=44}}},
    {true, {.leaf_idx=30}},
    {false, {.internal={.feature=9, .threshold_idx=63, .left=45, .right=46}}},
    {true, {.leaf_idx=29}},
    {true, {.leaf_idx=20}},
    {false, {.internal={.feature=4, .threshold_idx=30, .left=47, .right=48}}},
    {false, {.internal={.feature=5, .threshold_idx=29, .left=49, .right=50}}},
    {false, {.internal={.feature=7, .threshold_idx=42, .left=51, .right=52}}},
    {false, {.internal={.feature=8, .threshold_idx=43, .left=53, .right=54}}},
    {true, {.leaf_idx=18}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=2, .threshold_idx=55, .left=55, .right=56}}},
    {true, {.leaf_idx=29}},
    {true, {.leaf_idx=30}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=6, .threshold_idx=58, .left=57, .right=58}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=3, .threshold_idx=17, .left=59, .right=60}}},
    {true, {.leaf_idx=30}},
    {true, {.leaf_idx=17}},
    {true, {.leaf_idx=11}},
    {true, {.leaf_idx=19}},
    {true, {.leaf_idx=7}},
    {true, {.leaf_idx=26}},
    {true, {.leaf_idx=9}},
    {true, {.leaf_idx=22}},
    {false, {.internal={.feature=6, .threshold_idx=33, .left=1, .right=2}}},
    {false, {.internal={.feature=8, .threshold_idx=5, .left=3, .right=4}}},
    {false, {.internal={.feature=2, .threshold_idx=46, .left=5, .right=6}}},
    {false, {.internal={.feature=6, .threshold_idx=0, .left=7, .right=8}}},
    {false, {.internal={.feature=6, .threshold_idx=24, .left=9, .right=10}}},
    {false, {.internal={.feature=8, .threshold_idx=45, .left=11, .right=12}}},
    {false, {.internal={.feature=8, .threshold_idx=15, .left=13, .right=14}}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=15, .right=16}}},
    {false, {.internal={.feature=3, .threshold_idx=14, .left=17, .right=18}}},
    {false, {.internal={.feature=8, .threshold_idx=23, .left=19, .right=20}}},
    {true, {.leaf_idx=35}},
    {true, {.leaf_idx=31}},
    {false, {.internal={.feature=8, .threshold_idx=25, .left=21, .right=22}}},
    {false, {.internal={.feature=7, .threshold_idx=1, .left=23, .right=24}}},
    {false, {.internal={.feature=1, .threshold_idx=69, .left=25, .right=26}}},
    {false, {.internal={.feature=5, .threshold_idx=74, .left=27, .right=28}}},
    {false, {.internal={.feature=5, .threshold_idx=77, .left=29, .right=30}}},
    {true, {.leaf_idx=34}},
    {false, {.internal={.feature=5, .threshold_idx=51, .left=31, .right=32}}},
    {false, {.internal={.feature=4, .threshold_idx=7, .left=33, .right=34}}},
    {false, {.internal={.feature=0, .threshold_idx=47, .left=35, .right=36}}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=20}},
    {false, {.internal={.feature=6, .threshold_idx=14, .left=37, .right=38}}},
    {false, {.internal={.feature=0, .threshold_idx=61, .left=39, .right=40}}},
    {true, {.leaf_idx=13}},
    {false, {.internal={.feature=2, .threshold_idx=63, .left=41, .right=42}}},
    {true, {.leaf_idx=22}},
    {false, {.internal={.feature=3, .threshold_idx=16, .left=43, .right=44}}},
    {false, {.internal={.feature=0, .threshold_idx=32, .left=45, .right=46}}},
    {true, {.leaf_idx=18}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=9, .threshold_idx=55, .left=47, .right=48}}},
    {false, {.internal={.feature=6, .threshold_idx=49, .left=49, .right=50}}},
    {false, {.internal={.feature=9, .threshold_idx=70, .left=51, .right=52}}},
    {false, {.internal={.feature=0, .threshold_idx=59, .left=53, .right=54}}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=30}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=18}},
    {true, {.leaf_idx=17}},
    {false, {.internal={.feature=3, .threshold_idx=75, .left=55, .right=56}}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=8, .threshold_idx=34, .left=57, .right=58}}},
    {true, {.leaf_idx=9}},
    {true, {.leaf_idx=24}},
    {true, {.leaf_idx=33}},
    {false, {.internal={.feature=8, .threshold_idx=31, .left=59, .right=60}}},
    {true, {.leaf_idx=5}},
    {false, {.internal={.feature=0, .threshold_idx=63, .left=61, .right=62}}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=23}},
    {false, {.internal={.feature=0, .threshold_idx=44, .left=63, .right=64}}},
    {true, {.leaf_idx=20}},
    {true, {.leaf_idx=5}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=28}},
    {true, {.leaf_idx=7}},
    {true, {.leaf_idx=21}},
    {true, {.leaf_idx=32}},
    {true, {.leaf_idx=21}},
    {false, {.internal={.feature=6, .threshold_idx=38, .left=1, .right=2}}},
    {false, {.internal={.feature=8, .threshold_idx=4, .left=3, .right=4}}},
    {false, {.internal={.feature=2, .threshold_idx=34, .left=5, .right=6}}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=6, .threshold_idx=24, .left=7, .right=8}}},
    {false, {.internal={.feature=5, .threshold_idx=78, .left=9, .right=10}}},
    {false, {.internal={.feature=8, .threshold_idx=35, .left=11, .right=12}}},
    {false, {.internal={.feature=1, .threshold_idx=67, .left=13, .right=14}}},
    {false, {.internal={.feature=0, .threshold_idx=50, .left=15, .right=16}}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=23}},
    {false, {.internal={.feature=8, .threshold_idx=18, .left=17, .right=18}}},
    {false, {.internal={.feature=6, .threshold_idx=41, .left=19, .right=20}}},
    {false, {.internal={.feature=7, .threshold_idx=1, .left=21, .right=22}}},
    {false, {.internal={.feature=9, .threshold_idx=54, .left=23, .right=24}}},
    {true, {.leaf_idx=7}},
    {false, {.internal={.feature=8, .threshold_idx=20, .left=25, .right=26}}},
    {false, {.internal={.feature=7, .threshold_idx=73, .left=27, .right=28}}},
    {false, {.internal={.feature=6, .threshold_idx=39, .left=29, .right=30}}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=15}},
    {false, {.internal={.feature=3, .threshold_idx=12, .left=31, .right=32}}},
    {false, {.internal={.feature=6, .threshold_idx=18, .left=33, .right=34}}},
    {false, {.internal={.feature=7, .threshold_idx=36, .left=35, .right=36}}},
    {false, {.internal={.feature=2, .threshold_idx=63, .left=37, .right=38}}},
    {false, {.internal={.feature=1, .threshold_idx=35, .left=39, .right=40}}},
    {false, {.internal={.feature=4, .threshold_idx=3, .left=41, .right=42}}},
    {true, {.leaf_idx=23}},
    {true, {.leaf_idx=26}},
    {false, {.internal={.feature=9, .threshold_idx=13, .left=43, .right=44}}},
    {false, {.internal={.feature=3, .threshold_idx=10, .left=45, .right=46}}},
    {true, {.leaf_idx=4}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=14}},
    {true, {.leaf_idx=8}},
    {false, {.internal={.feature=7, .threshold_idx=46, .left=47, .right=48}}},
    {false, {.internal={.feature=7, .threshold_idx=15, .left=49, .right=50}}},
    {true, {.leaf_idx=20}},
    {true, {.leaf_idx=29}},
    {false, {.internal={.feature=9, .threshold_idx=63, .left=51, .right=52}}},
    {true, {.leaf_idx=23}},
    {false, {.internal={.feature=1, .threshold_idx=72, .left=53, .right=54}}},
    {false, {.internal={.feature=4, .threshold_idx=30, .left=55, .right=56}}},
    {false, {.internal={.feature=5, .threshold_idx=29, .left=57, .right=58}}},
    {false, {.internal={.feature=3, .threshold_idx=8, .left=59, .right=60}}},
    {true, {.leaf_idx=20}},
    {true, {.leaf_idx=25}},
    {false, {.internal={.feature=4, .threshold_idx=64, .left=61, .right=62}}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=3, .threshold_idx=30, .left=63, .right=64}}},
    {true, {.leaf_idx=28}},
    {true, {.leaf_idx=33}},
    {true, {.leaf_idx=23}},
    {true, {.leaf_idx=29}},
    {true, {.leaf_idx=14}},
    {false, {.internal={.feature=6, .threshold_idx=58, .left=65, .right=66}}},
    {true, {.leaf_idx=6}},
    {false, {.internal={.feature=9, .threshold_idx=19, .left=67, .right=68}}},
    {true, {.leaf_idx=16}},
    {false, {.internal={.feature=5, .threshold_idx=51, .left=69, .right=70}}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=12}},
    {true, {.leaf_idx=20}},
    {true, {.leaf_idx=8}},
    {true, {.leaf_idx=25}},
    {true, {.leaf_idx=16}},
    {true, {.leaf_idx=6}},
    {true, {.leaf_idx=13}},
    {true, {.leaf_idx=23}}
};


/* Tree metadata */
static const OptTree TREES[N_TREES] = {
    {0, 65},
    {65, 73},
    {138, 61},
    {199, 65},
    {264, 71}
};


/* Tree traversal function */
static inline float traverse_tree(int tree_id, const float* x) {
    const OptTree* tree = &TREES[tree_id];
    uint32_t node_idx = tree->start_idx;

    while (node_idx < tree->start_idx + tree->node_count) {
        const OptNode* node = &NODES[node_idx];

        if (node->is_leaf) {
            return SHARED_LEAVES[node->u.leaf_idx];
        }

        float threshold = SHARED_THRESHOLDS[node->u.internal.threshold_idx];

        if (x[node->u.internal.feature] < threshold) {
            node_idx = tree->start_idx + node->u.internal.left;
        } else {
            node_idx = tree->start_idx + node->u.internal.right;
        }
    }

    return 0.0f; /* Should never reach here */
}

float predict(const float* x) {
    float logit = -0.004000f;
    for (int i = 0; i < N_TREES; i++) {
        logit += traverse_tree(i, x);
    }
    return 1.0f / (1.0f + expf(-logit));
}

/*
// Memory breakdown:
// - Nodes: 2010 bytes (335 x 6)
// - Thresholds: 316 bytes (N_THRESHOLDS x 4)
// - Leaves: 156 bytes (N_LEAVES x 4)
// - Metadata: 30 bytes (N_TREES x (4 + 2))
// - Total: 2512 bytes
// Alignment: 4 bytes
// Feature type: uint8_t
// Threshold index type: uint8_t
// Node index type: uint8_t
// Leaf index type: uint8_t
*/


#ifdef __cplusplus
}
#endif

#endif /* EMBEDDED_TREES_MINIMAL_H */
